BdBundle\Entity\Editores:
    type: entity
    table: editores
    id:
        editorid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreEditorial:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: ''
            column: nombre_editorial
    lifecycleCallbacks: {  }
